# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  instance:
    hostname: flo-posms.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false

spring:
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    url: ${JDBC_DATABASE_URL}
  #    username: ${JDBC_DATABASE_USERNAME}
  #    password: ${JDBC_DATABASE_PASSWORD}
  #    hikari:
  #      maximumPoolSize: 8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:posms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: posms
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
server:
  port: ${PORT:8080}
